/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tempo;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import java.sql.*;
//import com.sun.jdi.connect.spi.Connection;
/**
 *
 * @author vsvnimish
 */
public class mainframe extends javax.swing.JFrame {

    
    /**
     * Creates new form mainframe
     */
    public mainframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        adminradiobutton = new javax.swing.JRadioButton();
        userradiobutton = new javax.swing.JRadioButton();
        okbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("select your role");

        adminradiobutton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adminradiobutton.setText("admin");
        adminradiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminradiobuttonActionPerformed(evt);
            }
        });

        userradiobutton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userradiobutton.setText("user");
        userradiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userradiobuttonActionPerformed(evt);
            }
        });

        okbutton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        okbutton.setText("ok");
        okbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(adminradiobutton)
                        .addGap(10, 10, 10)
                        .addComponent(userradiobutton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145))))
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(okbutton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminradiobutton)
                    .addComponent(userradiobutton))
                .addGap(29, 29, 29)
                .addComponent(okbutton)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminradiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminradiobuttonActionPerformed
        // TODO add your handling code here:
        System.out.println(adminradiobutton.isSelected());
         
      userradiobutton.setSelected(false);
        
    }//GEN-LAST:event_adminradiobuttonActionPerformed

    private void userradiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userradiobuttonActionPerformed
        // TODO add your handling code here:
        adminradiobutton.setSelected(false);
        ///////login or register
      
    }//GEN-LAST:event_userradiobuttonActionPerformed

    private void okbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okbuttonActionPerformed
        // TODO add your handling code here:
       //Connection c;
       
                if(adminradiobutton.isSelected()&&userradiobutton.isSelected()){
                    //System.out.println("cant slect both");
                    // Connection c;
                    //Class.forName("com.mysql.jdbc.Driver");
                    //  c = DriverManager.getConnection()
                    //dialogue box

                }
                else if(!adminradiobutton.isSelected()&&!userradiobutton.isSelected()){
                  System.out.println("slect atleast one");  
                  //dialogue box  
                }
                else if(adminradiobutton.isSelected()&&!userradiobutton.isSelected()){
                 /*this.toBack();
                  this.setVisible(false);
                  /*System.out.println("admin button");  */
                  adminpage ap=new adminpage();
                  ap.setVisible(true);
                  dispose();
                 // ap.toFront();
                  //dispose();
                   //new adminpage();
                 /*  JFrame f2=new JFrame();
                   f2.setVisible(true);
                   f2.setSize(400,400);*/
                   
                    
                }
                 else{
                  System.out.println("user button"); 
                    new loginorregister().setVisible(true);
                     dispose();
                }
                
                
        
            
    }//GEN-LAST:event_okbuttonActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.sql.SQLException
     */
    public static void main(String args[]) throws SQLException {
       
            try {
                
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
                * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                */
                // System.out.println("bn");
                Connection v;
                
                PreparedStatement con;
                
               Class.forName("com.mysql.cj.jdbc.Driver");
                v=DriverManager.getConnection("jdbc:mysql://localhost:3306/datatable","root","nimishraja");
               //if(v!=null) 
                // System.out.println("j");
                con=v.prepareStatement("select * from salary");
                ResultSet rs=con.executeQuery();
                ResultSetMetaData rss=rs.getMetaData();
                System.out.println(rss.getColumnCount());
                        
                
            //    con.setString(1,"845");
             //    con.setString(2,"845");
               //   con.setString(3,"845");
                
                
                
                
                try {
                    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                            javax.swing.UIManager.setLookAndFeel(info.getClassName());
                            break;
                        }
                    }
                } catch (ClassNotFoundException ex) {
                    java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                    java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>
                //</editor-fold>
                
                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new mainframe().setVisible(true);
                        
                         //dispose();
                    }
                });
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(mainframe.class.getName()).log(Level.SEVERE, null, ex);
            }
            //</editor-fold>
            //</editor-fold>
    }
        //</editor-fold>
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton adminradiobutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton okbutton;
    private javax.swing.JRadioButton userradiobutton;
    // End of variables declaration//GEN-END:variables
}
